name: ViaVersionProtocolSupport
version: 4.28-1.12.2-BETA-SNAPSHOT-767-340
main: 
description: This is a sample plugin.
author: YourName
commands:
  mycommand:
    description: This is a sample command.
    usage: /<command>
