name: ViaVersionProtocolSupport
version: 8.55-1.21.1-5.0.0
main: me.falixsrv.approximasteranarchy2004.ViaVersionProtocolSupport.ViaVersionProtocolSupportBukkit
description: This is a sample plugin.
author: YourName
